version: '3'
services:
  # server:
  #   build: .
  #   container_name: backend
  #   ports:
  #     - "5015:5015"
  #   restart: always
  client:
    build: ./client
    container_name: frontend
    ports:
      - "3000:3000"
    restart: always
